version: '3'

tasks:

  docs:
    desc: Generate the docs
    cmds:
      - go run cmd/help/main.go --dir docs/cli

  lint:
    desc: Run linting tools
    cmds:
      - golangci-lint run ./...
      - go vet ./...

  lint-fix:
    desc: Run linting tools, and apply fixes.
    cmds:
      - golangci-lint run --fix ./...

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  test-coverage:
    desc: Run tests with coverage analysis
    cmds:
      - mkdir -p coverage
      - go test -coverprofile=coverage/coverage.out ./...
      - go tool cover -func=coverage/coverage.out
      - echo "Generating HTML coverage report in coverage/coverage.html"
      - go tool cover -html=coverage/coverage.out -o coverage/coverage.html

  build:
    desc: Build the binary
    vars:
      VERSION:
        sh: git describe --tags --always --dirty || echo "dev"
      COMMIT:
        sh: git rev-parse --short HEAD || echo "unknown"
      BUILD_DATE:
        sh: date -u +"%Y-%m-%dT%H:%M:%SZ"
    cmds:
      - mkdir -p bin
      - go build -ldflags "-s -w -X github.com/stacklok/toolhive/cmd/thv/app.Version={{.VERSION}} -X github.com/stacklok/toolhive/cmd/thv/app.Commit={{.COMMIT}} -X github.com/stacklok/toolhive/cmd/thv/app.BuildDate={{.BUILD_DATE}}" -o bin/thv ./cmd/thv

  install:
    desc: Install the thv binary to GOPATH/bin
    vars:
      VERSION:
        sh: git describe --tags --always --dirty || echo "dev"
      COMMIT:
        sh: git rev-parse --short HEAD || echo "unknown"
      BUILD_DATE:
        sh: date -u +"%Y-%m-%dT%H:%M:%SZ"
    cmds:
      - go install -ldflags "-s -w -X github.com/stacklok/toolhive/pkg/versions.Version={{.VERSION}} -X github.com/stacklok/toolhive/pkg/versions.Commit={{.COMMIT}} -X github.com/stacklok/toolhive/pkg/versions.BuildDate={{.BUILD_DATE}}" -v ./cmd/thv

  all:
    desc: Run linting, tests, and build
    deps: [lint, test, build]

  all-with-coverage:
    desc: Run linting, tests with coverage, and build
    deps: [lint, test-coverage, build]

  build-image:
    desc: Build the image with ko
    env:
      KO_DOCKER_REPO: ghcr.io/stacklok/toolhive
    cmds:
      - ko build --local --bare ./cmd/thv

  kind-setup:
    desc: Setup a local Kind cluster
    cmds:
      - kind create cluster --name kind
      - kind get kubeconfig > kconfig.yaml

  kind-destroy:
    desc: Destroy a local Kind cluster
    cmds:
      - kind delete cluster --name kind
      - rm kconfig.yaml

  kind-ingress-setup:
    desc: Setup Nginx Ingress Controller in a local Kind cluster
    cmds:
      - echo "Applying Kubernetes Ingress manifest..."
      - kubectl apply -f https://kind.sigs.k8s.io/examples/ingress/deploy-ingress-nginx.yaml --kubeconfig kconfig.yaml
      - echo "Waiting for Ingress Nginx Controller to be created and ready..."
      - cmd: |
          while ! kubectl wait --namespace=ingress-nginx --for=condition=Ready pod --selector=app.kubernetes.io/instance=ingress-nginx,app.kubernetes.io/component=controller --timeout=120s --kubeconfig kconfig.yaml &>/dev/null; do sleep 2; done
        ignore_error: true
      # We do the below commands because of some inconsistency between the secret and webhook caBundle. ref: https://github.com/kubernetes/ingress-nginx/issues/5968#issuecomment-849772666
      - echo "Patching Ingress Nginx Admission Webhook CA Bundle..."
      - |
        CA=$(kubectl -n ingress-nginx get secret ingress-nginx-admission -ojsonpath='{.data.ca}' --kubeconfig kconfig.yaml)
        kubectl patch validatingwebhookconfigurations ingress-nginx-admission --type='json' --patch='[{"op":"add","path":"/webhooks/0/clientConfig/caBundle","value":"'$CA'"}]' --kubeconfig kconfig.yaml

  kind-with-toolhive-operator*:
    desc: |
      Setup a local Kind cluster with the ToolHive Operator installed. You can choose to deploy a locally built Operator image or the latest Operator image from Github.
      To deploy a locally built Operator image, run `task kind-with-toolhive-operator-local`.
      To deploy the latest Operator image from Github, run `task kind-with-toolhive-operator-latest`.
      By default, you can run `task kind-with-toolhive-operator` to deploy the latest Operator image from Github.
    vars:
      OPERATOR_DEPLOYMENT: '{{index .MATCH 0 | trimPrefix "-" | default "latest"}}'
    cmds:
      - task: kind-setup
      - task: kind-ingress-setup
      - task: operator-install-crds
      - task: operator-deploy-{{.OPERATOR_DEPLOYMENT}}

  # Operator tasks
  build-operator:
    desc: Build the operator binary
    vars:
      VERSION:
        sh: git describe --tags --always --dirty || echo "dev"
      COMMIT:
        sh: git rev-parse --short HEAD || echo "unknown"
      BUILD_DATE:
        sh: date -u +"%Y-%m-%dT%H:%M:%SZ"
    cmds:
      - mkdir -p bin
      - go build -ldflags "-s -w -X github.com/stacklok/toolhive/cmd/thv-operator/app.Version={{.VERSION}} -X github.com/stacklok/toolhive/cmd/thv-operator/app.Commit={{.COMMIT}} -X github.com/stacklok/toolhive/cmd/thv-operator/app.BuildDate={{.BUILD_DATE}}" -o bin/thv-operator ./cmd/thv-operator

  install-operator:
    desc: Install the thv-operator binary to GOPATH/bin
    vars:
      VERSION:
        sh: git describe --tags --always --dirty || echo "dev"
      COMMIT:
        sh: git rev-parse --short HEAD || echo "unknown"
      BUILD_DATE:
        sh: date -u +"%Y-%m-%dT%H:%M:%SZ"
    cmds:
      - go install -ldflags "-s -w -X github.com/stacklok/toolhive/cmd/thv-operator/app.Version={{.VERSION}} -X github.com/stacklok/toolhive/cmd/thv-operator/app.Commit={{.COMMIT}} -X github.com/stacklok/toolhive/cmd/thv-operator/app.BuildDate={{.BUILD_DATE}}" -v ./cmd/thv-operator

  build-operator-image:
    desc: Build the operator image with ko
    cmds:
      - ko build --platform linux/amd64,linux/arm64 --local ./cmd/thv-operator

  operator-install-crds:
    desc: Install CRDs into the K8s cluster
    cmds:
      - kubectl apply -f deploy/operator/crds/toolhive.stacklok.dev_mcpservers.yaml --server-side=true --kubeconfig kconfig.yaml

  operator-uninstall-crds:
    desc: Uninstall CRDs from the K8s cluster
    cmds:
      - kubectl delete -f deploy/operator/crds/toolhive.stacklok.dev_mcpservers.yaml

  operator-deploy-latest:
    desc: Deploy latest built Operator image from Github to the K8s cluster
    cmds:
      - kubectl apply -f deploy/operator/namespace.yaml --kubeconfig kconfig.yaml
      - kubectl apply -f deploy/operator/rbac.yaml --kubeconfig kconfig.yaml
      - kubectl apply -f deploy/operator/toolhive_rbac.yaml --kubeconfig kconfig.yaml
      - kubectl apply -f deploy/operator/operator.yaml --kubeconfig kconfig.yaml

  operator-deploy-local:
    desc: Build the Operator image locally and deploy it to the K8s cluster
    vars:
      IMAGE:
        sh: KO_DOCKER_REPO=kind.local ko build --platform linux/amd64 --local -B ./cmd/thv-operator | tail -n 1
    cmds:
      - echo "Loading image {{.IMAGE}} into kind..."
      - kind load docker-image {{.IMAGE}}
      - kubectl apply -f deploy/operator/namespace.yaml --kubeconfig kconfig.yaml
      - kubectl apply -f deploy/operator/rbac.yaml --kubeconfig kconfig.yaml
      - kubectl apply -f deploy/operator/toolhive_rbac.yaml --kubeconfig kconfig.yaml
      - kubectl apply -f <(KO_DOCKER_REPO=kind.local ko resolve --platform linux/amd64 -B -f deploy/operator/operator_local.yaml) --kubeconfig kconfig.yaml

  operator-undeploy:
    desc: Undeploy operator from the K8s cluster
    cmds:
      - kubectl delete -f deploy/operator/operator.yaml --kubeconfig kconfig.yaml
      - kubectl delete -f deploy/operator/rbac.yaml --kubeconfig kconfig.yaml
      - kubectl delete -f deploy/operator/toolhive_rbac.yaml --kubeconfig kconfig.yaml
      - kubectl delete -f deploy/operator/namespace.yaml --kubeconfig kconfig.yaml

  # Kubebuilder tasks
  operator-generate:
    desc: Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations
    cmds:
      - mkdir -p bin
      - go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.17.3
      - $(go env GOPATH)/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./cmd/thv-operator/..."

  operator-manifests:
    desc: Generate WebhookConfiguration, ClusterRole and CustomResourceDefinition objects
    cmds:
      - mkdir -p bin
      - go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.17.3
      - $(go env GOPATH)/bin/controller-gen crd webhook paths="./cmd/thv-operator/..." output:crd:artifacts:config=deploy/charts/operator-crds/templates
      - $(go env GOPATH)/bin/controller-gen rbac:roleName=toolhive-operator-manager-role paths="./cmd/thv-operator/..." output:rbac:artifacts:config=deploy/charts/operator/templates/clusterrole

  operator-test:
    desc: Run tests for the operator
    cmds:
      - go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
      - KUBEBUILDER_ASSETS="$(shell setup-envtest use 1.28.0 -p path)" go test ./cmd/thv-operator/... -coverprofile cover.out
