{{- if .Values.operator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: toolhive-operator
    app.kubernetes.io/part-of: toolhive-operator
  {{- if .Values.operator.serviceAccount.labels }}
    {{- toYaml .Values.operator.serviceAccount.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.operator.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.operator.serviceAccount.annotations | nindent 12 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.operator.serviceAccount.automountServiceAccountToken }}
{{- end }}
