apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: mkp
  namespace: toolhive-system
spec:
  image: ghcr.io/stackloklabs/mkp/server
  transport: sse
  port: 8080
  permissionProfile:
    type: builtin
    name: network
  # Example of using the PodTemplateSpec to customize the pod
  podTemplateSpec:
    spec:
      # this value has to be set to a serviceaccount that has the necessary permissions
      # will use the default toolhive service account for an example
      serviceAccountName: toolhive
      containers:
      - name: mcp
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "50m"
      memory: "64Mi"