# These set of workflows run on every push to the main branch
name: PR Checks

on:
  workflow_dispatch:
  pull_request:

jobs:
  linting:
    name: Linting
    uses: ./.github/workflows/lint.yml
  tests:
    name: Tests
    uses: ./.github/workflows/test.yml
  docs:
    name: Docs
    uses: ./.github/workflows/verify-docgen.yml
