name: Test Charts

permissions:
  contents: read

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # pin@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@5b950139b732971f3c4338f6d8bdc2015a47661c # pin@v4.3.0
        with:
          version: v3.10.0

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # pin@v5
        with:
          python-version: 3.12

      - name: Set up chart-testing
        uses: helm/chart-testing-action@0d28d3144d3a25ea2cc349d6e59901c4ff469b3b # pin@v2.3.0

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml

      - name: Create KIND Cluster
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # pin@v1.12.0

      - name: Run chart-testing (install)
        run: ct install --config ct-install.yaml