name: Trigger Docs Update

permissions:
  contents: read

on:
  release:
    types: [published]

jobs:
  trigger:
    # Don't trigger on operator releases
    # On a release event, ref is the release tag
    if: ${{ startsWith(github.event.release.tag_name, 'v') }}
    runs-on: ubuntu-latest

    steps:
      - name: Trigger docs update workflow
        run: |
          repo="stacklok/docs-website"
          event_type="published-release"
          version="${{ github.event.release.tag_name }}"

          echo "Triggering docs update for $repo with version $version"
  
          curl --fail -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DOCS_REPO_DISPATCH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"version\": \"$version\"}}"
